# Generated by Django 5.1.7 on 2025-03-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lengua_house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('booked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('booked_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AvailableSlot',
        ),
    ]
