# Generated by Django 5.1.7 on 2025-03-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lengua_house', '0002_tutorschedule_delete_availableslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorschedule',
            name='time',
            field=models.CharField(choices=[('09:00:00', '09:00 AM'), ('10:00:00', '10:00 AM'), ('11:00:00', '11:00 AM'), ('14:00:00', '02:00 AM'), ('15:00:00', '03:00 AM'), ('16:00:00', '04:00 AM')], max_length=10),
        ),
    ]
